#!/usr/bin/env python3
"""Generate or verify the paper statistics displayed in README.md."""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Mapping
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_README = ROOT / "README.md"

PAPERS_HEADING = "## Papers"
STATS_START = "<!-- PAPER_STATS_START -->"
STATS_END = "<!-- PAPER_STATS_END -->"

SECTION_RE = re.compile(r"^##\s+")
YEAR_RE = re.compile(r"^###\s+((?:19|20)\d{2})\s*$")
PAPER_ENTRY_RE = re.compile(r"^(?:-|\*)\s+\S")


def count_papers(readme: str) -> dict[str, int]:
    """Count top-level paper entries under each year in the Papers section."""
    counts: dict[str, int] = {}
    in_papers = False
    found_papers = False
    current_year: str | None = None

    for line_number, line in enumerate(readme.splitlines(), start=1):
        if line == PAPERS_HEADING:
            if found_papers:
                raise ValueError(f"Duplicate {PAPERS_HEADING!r} heading")
            found_papers = True
            in_papers = True
            continue

        if not in_papers:
            continue

        if SECTION_RE.match(line):
            break

        year_match = YEAR_RE.match(line)
        if year_match:
            current_year = year_match.group(1)
            if current_year in counts:
                raise ValueError(f"Duplicate paper year {current_year}")
            counts[current_year] = 0
            continue

        if PAPER_ENTRY_RE.match(line):
            if current_year is None:
                raise ValueError(
                    f"Paper entry before the first year heading at line {line_number}"
                )
            counts[current_year] += 1

    if not found_papers:
        raise ValueError(f"Missing {PAPERS_HEADING!r} heading")
    if not counts:
        raise ValueError("No paper year headings found")

    empty_years = [year for year, count in counts.items() if count == 0]
    if empty_years:
        raise ValueError(f"Paper years without entries: {', '.join(empty_years)}")

    return counts


def render_statistics(counts: Mapping[str, int]) -> str:
    """Render the generated Markdown statistics block."""
    total = sum(counts.values())
    rows = [
        STATS_START,
        "<!-- Generated by scripts/update_paper_stats.py. Do not edit manually. -->",
        f"**Paper count:** **{total}**",
        "",
        "| Year | Papers |",
        "| --- | ---: |",
    ]
    rows.extend(f"| {year} | {count} |" for year, count in counts.items())
    rows.extend((f"| **Total** | **{total}** |", STATS_END))
    return "\n".join(rows)


def update_statistics(readme: str) -> str:
    """Replace the generated statistics block with current counts."""
    if readme.count(STATS_START) != 1 or readme.count(STATS_END) != 1:
        raise ValueError("README must contain exactly one paper statistics block")

    start = readme.index(STATS_START)
    end = readme.index(STATS_END, start) + len(STATS_END)
    if end <= start:
        raise ValueError("Invalid paper statistics marker order")

    block = render_statistics(count_papers(readme))
    return f"{readme[:start]}{block}{readme[end:]}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update or verify generated paper statistics in README.md."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the generated statistics are stale",
    )
    parser.add_argument(
        "--readme",
        type=Path,
        default=DEFAULT_README,
        help="README file to process",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    readme_path = args.readme.resolve()

    try:
        original = readme_path.read_text(encoding="utf-8")
        updated = update_statistics(original)
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if updated == original:
        print("Paper statistics are up to date.")
        return 0

    if args.check:
        print(
            "Paper statistics are stale. "
            "Run `python3 scripts/update_paper_stats.py`.",
            file=sys.stderr,
        )
        return 1

    try:
        readme_path.write_text(updated, encoding="utf-8")
    except OSError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    total = sum(count_papers(updated).values())
    print(f"Updated paper statistics for {total} papers.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
